name: firestore_repository
description: A new Flutter package project.
version: 0.0.2
homepage: https://github.com/tedcrimson/firestore_repository

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.3.0
  cloud_firestore: ^4.6.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.0
  rxdart: ^0.26.0

