name: firestore_repository
description: A new Flutter package project.
version: 0.0.1+1
homepage: https://github.com:tedcrimson/firestore_repository

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.1
  cloud_firestore: ^0.14.2
  bloc: ^6.1.0
  flutter_bloc: ^6.0.6
  equatable: ^1.2.5
  rxdart: ^0.24.1
